/**
 * generated by Xtext 2.21.0
 */
package xtext.robocode.generator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.robocode.generator.Action#getComment <em>Comment</em>}</li>
 *   <li>{@link xtext.robocode.generator.Action#isIsSetter <em>Is Setter</em>}</li>
 *   <li>{@link xtext.robocode.generator.Action#isIsGetter <em>Is Getter</em>}</li>
 *   <li>{@link xtext.robocode.generator.Action#getFunctionName <em>Function Name</em>}</li>
 *   <li>{@link xtext.robocode.generator.Action#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see xtext.robocode.generator.GeneratorPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comment</em>' attribute.
   * @see #setComment(String)
   * @see xtext.robocode.generator.GeneratorPackage#getAction_Comment()
   * @model
   * @generated
   */
  String getComment();

  /**
   * Sets the value of the '{@link xtext.robocode.generator.Action#getComment <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comment</em>' attribute.
   * @see #getComment()
   * @generated
   */
  void setComment(String value);

  /**
   * Returns the value of the '<em><b>Is Setter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Setter</em>' attribute.
   * @see #setIsSetter(boolean)
   * @see xtext.robocode.generator.GeneratorPackage#getAction_IsSetter()
   * @model
   * @generated
   */
  boolean isIsSetter();

  /**
   * Sets the value of the '{@link xtext.robocode.generator.Action#isIsSetter <em>Is Setter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Setter</em>' attribute.
   * @see #isIsSetter()
   * @generated
   */
  void setIsSetter(boolean value);

  /**
   * Returns the value of the '<em><b>Is Getter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Getter</em>' attribute.
   * @see #setIsGetter(boolean)
   * @see xtext.robocode.generator.GeneratorPackage#getAction_IsGetter()
   * @model
   * @generated
   */
  boolean isIsGetter();

  /**
   * Sets the value of the '{@link xtext.robocode.generator.Action#isIsGetter <em>Is Getter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Getter</em>' attribute.
   * @see #isIsGetter()
   * @generated
   */
  void setIsGetter(boolean value);

  /**
   * Returns the value of the '<em><b>Function Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Name</em>' attribute.
   * @see #setFunctionName(String)
   * @see xtext.robocode.generator.GeneratorPackage#getAction_FunctionName()
   * @model
   * @generated
   */
  String getFunctionName();

  /**
   * Sets the value of the '{@link xtext.robocode.generator.Action#getFunctionName <em>Function Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Name</em>' attribute.
   * @see #getFunctionName()
   * @generated
   */
  void setFunctionName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' attribute.
   * @see #setParameters(String)
   * @see xtext.robocode.generator.GeneratorPackage#getAction_Parameters()
   * @model
   * @generated
   */
  String getParameters();

  /**
   * Sets the value of the '{@link xtext.robocode.generator.Action#getParameters <em>Parameters</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameters</em>' attribute.
   * @see #getParameters()
   * @generated
   */
  void setParameters(String value);

} // Action
