/**
 * generated by Xtext 2.21.0
 */
package xtext.robocode.generator;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Advanced Robot</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.robocode.generator.GeneratorPackage#getAdvancedRobot()
 * @model
 * @generated
 */
public interface AdvancedRobot extends Robot
{
} // AdvancedRobot
