/**
 * generated by Xtext 2.21.0
 */
package xtext.robocode.generator;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arena</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.robocode.generator.Arena#getRobot <em>Robot</em>}</li>
 * </ul>
 *
 * @see xtext.robocode.generator.GeneratorPackage#getArena()
 * @model
 * @generated
 */
public interface Arena extends EObject
{
  /**
   * Returns the value of the '<em><b>Robot</b></em>' containment reference list.
   * The list contents are of type {@link xtext.robocode.generator.Robot}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robot</em>' containment reference list.
   * @see xtext.robocode.generator.GeneratorPackage#getArena_Robot()
   * @model containment="true"
   * @generated
   */
  EList<Robot> getRobot();

} // Arena
