/**
 * generated by Xtext 2.21.0
 */
package xtext.robocode.generator;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see xtext.robocode.generator.GeneratorFactory
 * @model kind="package"
 * @generated
 */
public interface GeneratorPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "generator";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.robocode.xtext/Generator";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "generator";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GeneratorPackage eINSTANCE = xtext.robocode.generator.impl.GeneratorPackageImpl.init();

  /**
   * The meta object id for the '{@link xtext.robocode.generator.impl.ArenaImpl <em>Arena</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.robocode.generator.impl.ArenaImpl
   * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getArena()
   * @generated
   */
  int ARENA = 0;

  /**
   * The feature id for the '<em><b>Robot</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARENA__ROBOT = 0;

  /**
   * The number of structural features of the '<em>Arena</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARENA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.robocode.generator.impl.RobotImpl <em>Robot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.robocode.generator.impl.RobotImpl
   * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getRobot()
   * @generated
   */
  int ROBOT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__NAME = 0;

  /**
   * The feature id for the '<em><b>Events Handled</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__EVENTS_HANDLED = 1;

  /**
   * The feature id for the '<em><b>Run Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__RUN_ACTIONS = 2;

  /**
   * The feature id for the '<em><b>Infinite Loop Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__INFINITE_LOOP_ACTIONS = 3;

  /**
   * The number of structural features of the '<em>Robot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link xtext.robocode.generator.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.robocode.generator.impl.EventImpl
   * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 2;

  /**
   * The feature id for the '<em><b>Event Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__EVENT_TYPE = 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__ACTIONS = 1;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.robocode.generator.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.robocode.generator.impl.ActionImpl
   * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getAction()
   * @generated
   */
  int ACTION = 3;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__COMMENT = 0;

  /**
   * The feature id for the '<em><b>Is Setter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__IS_SETTER = 1;

  /**
   * The feature id for the '<em><b>Is Getter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__IS_GETTER = 2;

  /**
   * The feature id for the '<em><b>Function Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__FUNCTION_NAME = 3;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__PARAMETERS = 4;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link xtext.robocode.generator.impl.AdvancedRobotImpl <em>Advanced Robot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.robocode.generator.impl.AdvancedRobotImpl
   * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getAdvancedRobot()
   * @generated
   */
  int ADVANCED_ROBOT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADVANCED_ROBOT__NAME = ROBOT__NAME;

  /**
   * The feature id for the '<em><b>Events Handled</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADVANCED_ROBOT__EVENTS_HANDLED = ROBOT__EVENTS_HANDLED;

  /**
   * The feature id for the '<em><b>Run Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADVANCED_ROBOT__RUN_ACTIONS = ROBOT__RUN_ACTIONS;

  /**
   * The feature id for the '<em><b>Infinite Loop Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADVANCED_ROBOT__INFINITE_LOOP_ACTIONS = ROBOT__INFINITE_LOOP_ACTIONS;

  /**
   * The number of structural features of the '<em>Advanced Robot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADVANCED_ROBOT_FEATURE_COUNT = ROBOT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xtext.robocode.generator.impl.RangeControlRobotImpl <em>Range Control Robot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.robocode.generator.impl.RangeControlRobotImpl
   * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getRangeControlRobot()
   * @generated
   */
  int RANGE_CONTROL_ROBOT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_CONTROL_ROBOT__NAME = ROBOT__NAME;

  /**
   * The feature id for the '<em><b>Events Handled</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_CONTROL_ROBOT__EVENTS_HANDLED = ROBOT__EVENTS_HANDLED;

  /**
   * The feature id for the '<em><b>Run Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_CONTROL_ROBOT__RUN_ACTIONS = ROBOT__RUN_ACTIONS;

  /**
   * The feature id for the '<em><b>Infinite Loop Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_CONTROL_ROBOT__INFINITE_LOOP_ACTIONS = ROBOT__INFINITE_LOOP_ACTIONS;

  /**
   * The number of structural features of the '<em>Range Control Robot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_CONTROL_ROBOT_FEATURE_COUNT = ROBOT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xtext.robocode.generator.EventType <em>Event Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.robocode.generator.EventType
   * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getEventType()
   * @generated
   */
  int EVENT_TYPE = 6;


  /**
   * Returns the meta object for class '{@link xtext.robocode.generator.Arena <em>Arena</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arena</em>'.
   * @see xtext.robocode.generator.Arena
   * @generated
   */
  EClass getArena();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.robocode.generator.Arena#getRobot <em>Robot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Robot</em>'.
   * @see xtext.robocode.generator.Arena#getRobot()
   * @see #getArena()
   * @generated
   */
  EReference getArena_Robot();

  /**
   * Returns the meta object for class '{@link xtext.robocode.generator.Robot <em>Robot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Robot</em>'.
   * @see xtext.robocode.generator.Robot
   * @generated
   */
  EClass getRobot();

  /**
   * Returns the meta object for the attribute '{@link xtext.robocode.generator.Robot#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.robocode.generator.Robot#getName()
   * @see #getRobot()
   * @generated
   */
  EAttribute getRobot_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.robocode.generator.Robot#getEventsHandled <em>Events Handled</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events Handled</em>'.
   * @see xtext.robocode.generator.Robot#getEventsHandled()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_EventsHandled();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.robocode.generator.Robot#getRunActions <em>Run Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Run Actions</em>'.
   * @see xtext.robocode.generator.Robot#getRunActions()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_RunActions();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.robocode.generator.Robot#getInfiniteLoopActions <em>Infinite Loop Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Infinite Loop Actions</em>'.
   * @see xtext.robocode.generator.Robot#getInfiniteLoopActions()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_InfiniteLoopActions();

  /**
   * Returns the meta object for class '{@link xtext.robocode.generator.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see xtext.robocode.generator.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link xtext.robocode.generator.Event#getEventType <em>Event Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Event Type</em>'.
   * @see xtext.robocode.generator.Event#getEventType()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_EventType();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.robocode.generator.Event#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see xtext.robocode.generator.Event#getActions()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Actions();

  /**
   * Returns the meta object for class '{@link xtext.robocode.generator.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see xtext.robocode.generator.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link xtext.robocode.generator.Action#getComment <em>Comment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comment</em>'.
   * @see xtext.robocode.generator.Action#getComment()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Comment();

  /**
   * Returns the meta object for the attribute '{@link xtext.robocode.generator.Action#isIsSetter <em>Is Setter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Setter</em>'.
   * @see xtext.robocode.generator.Action#isIsSetter()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_IsSetter();

  /**
   * Returns the meta object for the attribute '{@link xtext.robocode.generator.Action#isIsGetter <em>Is Getter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Getter</em>'.
   * @see xtext.robocode.generator.Action#isIsGetter()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_IsGetter();

  /**
   * Returns the meta object for the attribute '{@link xtext.robocode.generator.Action#getFunctionName <em>Function Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Function Name</em>'.
   * @see xtext.robocode.generator.Action#getFunctionName()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_FunctionName();

  /**
   * Returns the meta object for the attribute '{@link xtext.robocode.generator.Action#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parameters</em>'.
   * @see xtext.robocode.generator.Action#getParameters()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Parameters();

  /**
   * Returns the meta object for class '{@link xtext.robocode.generator.AdvancedRobot <em>Advanced Robot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Advanced Robot</em>'.
   * @see xtext.robocode.generator.AdvancedRobot
   * @generated
   */
  EClass getAdvancedRobot();

  /**
   * Returns the meta object for class '{@link xtext.robocode.generator.RangeControlRobot <em>Range Control Robot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range Control Robot</em>'.
   * @see xtext.robocode.generator.RangeControlRobot
   * @generated
   */
  EClass getRangeControlRobot();

  /**
   * Returns the meta object for enum '{@link xtext.robocode.generator.EventType <em>Event Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Event Type</em>'.
   * @see xtext.robocode.generator.EventType
   * @generated
   */
  EEnum getEventType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GeneratorFactory getGeneratorFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link xtext.robocode.generator.impl.ArenaImpl <em>Arena</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.robocode.generator.impl.ArenaImpl
     * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getArena()
     * @generated
     */
    EClass ARENA = eINSTANCE.getArena();

    /**
     * The meta object literal for the '<em><b>Robot</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARENA__ROBOT = eINSTANCE.getArena_Robot();

    /**
     * The meta object literal for the '{@link xtext.robocode.generator.impl.RobotImpl <em>Robot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.robocode.generator.impl.RobotImpl
     * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getRobot()
     * @generated
     */
    EClass ROBOT = eINSTANCE.getRobot();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT__NAME = eINSTANCE.getRobot_Name();

    /**
     * The meta object literal for the '<em><b>Events Handled</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__EVENTS_HANDLED = eINSTANCE.getRobot_EventsHandled();

    /**
     * The meta object literal for the '<em><b>Run Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__RUN_ACTIONS = eINSTANCE.getRobot_RunActions();

    /**
     * The meta object literal for the '<em><b>Infinite Loop Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__INFINITE_LOOP_ACTIONS = eINSTANCE.getRobot_InfiniteLoopActions();

    /**
     * The meta object literal for the '{@link xtext.robocode.generator.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.robocode.generator.impl.EventImpl
     * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Event Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__EVENT_TYPE = eINSTANCE.getEvent_EventType();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__ACTIONS = eINSTANCE.getEvent_Actions();

    /**
     * The meta object literal for the '{@link xtext.robocode.generator.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.robocode.generator.impl.ActionImpl
     * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Comment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__COMMENT = eINSTANCE.getAction_Comment();

    /**
     * The meta object literal for the '<em><b>Is Setter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__IS_SETTER = eINSTANCE.getAction_IsSetter();

    /**
     * The meta object literal for the '<em><b>Is Getter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__IS_GETTER = eINSTANCE.getAction_IsGetter();

    /**
     * The meta object literal for the '<em><b>Function Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__FUNCTION_NAME = eINSTANCE.getAction_FunctionName();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__PARAMETERS = eINSTANCE.getAction_Parameters();

    /**
     * The meta object literal for the '{@link xtext.robocode.generator.impl.AdvancedRobotImpl <em>Advanced Robot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.robocode.generator.impl.AdvancedRobotImpl
     * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getAdvancedRobot()
     * @generated
     */
    EClass ADVANCED_ROBOT = eINSTANCE.getAdvancedRobot();

    /**
     * The meta object literal for the '{@link xtext.robocode.generator.impl.RangeControlRobotImpl <em>Range Control Robot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.robocode.generator.impl.RangeControlRobotImpl
     * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getRangeControlRobot()
     * @generated
     */
    EClass RANGE_CONTROL_ROBOT = eINSTANCE.getRangeControlRobot();

    /**
     * The meta object literal for the '{@link xtext.robocode.generator.EventType <em>Event Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.robocode.generator.EventType
     * @see xtext.robocode.generator.impl.GeneratorPackageImpl#getEventType()
     * @generated
     */
    EEnum EVENT_TYPE = eINSTANCE.getEventType();

  }

} //GeneratorPackage
