/**
 * generated by Xtext 2.21.0
 */
package xtext.robocode.generator;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robot</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.robocode.generator.Robot#getName <em>Name</em>}</li>
 *   <li>{@link xtext.robocode.generator.Robot#getEventsHandled <em>Events Handled</em>}</li>
 *   <li>{@link xtext.robocode.generator.Robot#getRunActions <em>Run Actions</em>}</li>
 *   <li>{@link xtext.robocode.generator.Robot#getInfiniteLoopActions <em>Infinite Loop Actions</em>}</li>
 * </ul>
 *
 * @see xtext.robocode.generator.GeneratorPackage#getRobot()
 * @model
 * @generated
 */
public interface Robot extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.robocode.generator.GeneratorPackage#getRobot_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.robocode.generator.Robot#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Events Handled</b></em>' containment reference list.
   * The list contents are of type {@link xtext.robocode.generator.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events Handled</em>' containment reference list.
   * @see xtext.robocode.generator.GeneratorPackage#getRobot_EventsHandled()
   * @model containment="true"
   * @generated
   */
  EList<Event> getEventsHandled();

  /**
   * Returns the value of the '<em><b>Run Actions</b></em>' containment reference list.
   * The list contents are of type {@link xtext.robocode.generator.Action}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Run Actions</em>' containment reference list.
   * @see xtext.robocode.generator.GeneratorPackage#getRobot_RunActions()
   * @model containment="true"
   * @generated
   */
  EList<Action> getRunActions();

  /**
   * Returns the value of the '<em><b>Infinite Loop Actions</b></em>' containment reference list.
   * The list contents are of type {@link xtext.robocode.generator.Action}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Infinite Loop Actions</em>' containment reference list.
   * @see xtext.robocode.generator.GeneratorPackage#getRobot_InfiniteLoopActions()
   * @model containment="true"
   * @generated
   */
  EList<Action> getInfiniteLoopActions();

} // Robot
