/*
 * generated by Xtext 2.21.0
 */
package xtext.robocode.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGeneratorScopeProvider extends DelegatingScopeProvider {
}
