/*
 * generated by Xtext 2.21.0
 */
package xtext.robocode;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GeneratorStandaloneSetup extends GeneratorStandaloneSetupGenerated {

	public static void doSetup() {
		new GeneratorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
