/**
 * generated by Xtext 2.21.0
 */
package xtext.robocode.generator.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import xtext.robocode.generator.Action;
import xtext.robocode.generator.GeneratorPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.robocode.generator.impl.ActionImpl#getComment <em>Comment</em>}</li>
 *   <li>{@link xtext.robocode.generator.impl.ActionImpl#isIsSetter <em>Is Setter</em>}</li>
 *   <li>{@link xtext.robocode.generator.impl.ActionImpl#isIsGetter <em>Is Getter</em>}</li>
 *   <li>{@link xtext.robocode.generator.impl.ActionImpl#getFunctionName <em>Function Name</em>}</li>
 *   <li>{@link xtext.robocode.generator.impl.ActionImpl#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ActionImpl extends MinimalEObjectImpl.Container implements Action
{
  /**
   * The default value of the '{@link #getComment() <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComment()
   * @generated
   * @ordered
   */
  protected static final String COMMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getComment() <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComment()
   * @generated
   * @ordered
   */
  protected String comment = COMMENT_EDEFAULT;

  /**
   * The default value of the '{@link #isIsSetter() <em>Is Setter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsSetter()
   * @generated
   * @ordered
   */
  protected static final boolean IS_SETTER_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsSetter() <em>Is Setter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsSetter()
   * @generated
   * @ordered
   */
  protected boolean isSetter = IS_SETTER_EDEFAULT;

  /**
   * The default value of the '{@link #isIsGetter() <em>Is Getter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsGetter()
   * @generated
   * @ordered
   */
  protected static final boolean IS_GETTER_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsGetter() <em>Is Getter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsGetter()
   * @generated
   * @ordered
   */
  protected boolean isGetter = IS_GETTER_EDEFAULT;

  /**
   * The default value of the '{@link #getFunctionName() <em>Function Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunctionName()
   * @generated
   * @ordered
   */
  protected static final String FUNCTION_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFunctionName() <em>Function Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunctionName()
   * @generated
   * @ordered
   */
  protected String functionName = FUNCTION_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getParameters() <em>Parameters</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameters()
   * @generated
   * @ordered
   */
  protected static final String PARAMETERS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getParameters() <em>Parameters</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameters()
   * @generated
   * @ordered
   */
  protected String parameters = PARAMETERS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GeneratorPackage.Literals.ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getComment()
  {
    return comment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setComment(String newComment)
  {
    String oldComment = comment;
    comment = newComment;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneratorPackage.ACTION__COMMENT, oldComment, comment));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsSetter()
  {
    return isSetter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsSetter(boolean newIsSetter)
  {
    boolean oldIsSetter = isSetter;
    isSetter = newIsSetter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneratorPackage.ACTION__IS_SETTER, oldIsSetter, isSetter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsGetter()
  {
    return isGetter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsGetter(boolean newIsGetter)
  {
    boolean oldIsGetter = isGetter;
    isGetter = newIsGetter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneratorPackage.ACTION__IS_GETTER, oldIsGetter, isGetter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFunctionName()
  {
    return functionName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFunctionName(String newFunctionName)
  {
    String oldFunctionName = functionName;
    functionName = newFunctionName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneratorPackage.ACTION__FUNCTION_NAME, oldFunctionName, functionName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getParameters()
  {
    return parameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParameters(String newParameters)
  {
    String oldParameters = parameters;
    parameters = newParameters;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneratorPackage.ACTION__PARAMETERS, oldParameters, parameters));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GeneratorPackage.ACTION__COMMENT:
        return getComment();
      case GeneratorPackage.ACTION__IS_SETTER:
        return isIsSetter();
      case GeneratorPackage.ACTION__IS_GETTER:
        return isIsGetter();
      case GeneratorPackage.ACTION__FUNCTION_NAME:
        return getFunctionName();
      case GeneratorPackage.ACTION__PARAMETERS:
        return getParameters();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GeneratorPackage.ACTION__COMMENT:
        setComment((String)newValue);
        return;
      case GeneratorPackage.ACTION__IS_SETTER:
        setIsSetter((Boolean)newValue);
        return;
      case GeneratorPackage.ACTION__IS_GETTER:
        setIsGetter((Boolean)newValue);
        return;
      case GeneratorPackage.ACTION__FUNCTION_NAME:
        setFunctionName((String)newValue);
        return;
      case GeneratorPackage.ACTION__PARAMETERS:
        setParameters((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GeneratorPackage.ACTION__COMMENT:
        setComment(COMMENT_EDEFAULT);
        return;
      case GeneratorPackage.ACTION__IS_SETTER:
        setIsSetter(IS_SETTER_EDEFAULT);
        return;
      case GeneratorPackage.ACTION__IS_GETTER:
        setIsGetter(IS_GETTER_EDEFAULT);
        return;
      case GeneratorPackage.ACTION__FUNCTION_NAME:
        setFunctionName(FUNCTION_NAME_EDEFAULT);
        return;
      case GeneratorPackage.ACTION__PARAMETERS:
        setParameters(PARAMETERS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GeneratorPackage.ACTION__COMMENT:
        return COMMENT_EDEFAULT == null ? comment != null : !COMMENT_EDEFAULT.equals(comment);
      case GeneratorPackage.ACTION__IS_SETTER:
        return isSetter != IS_SETTER_EDEFAULT;
      case GeneratorPackage.ACTION__IS_GETTER:
        return isGetter != IS_GETTER_EDEFAULT;
      case GeneratorPackage.ACTION__FUNCTION_NAME:
        return FUNCTION_NAME_EDEFAULT == null ? functionName != null : !FUNCTION_NAME_EDEFAULT.equals(functionName);
      case GeneratorPackage.ACTION__PARAMETERS:
        return PARAMETERS_EDEFAULT == null ? parameters != null : !PARAMETERS_EDEFAULT.equals(parameters);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (comment: ");
    result.append(comment);
    result.append(", isSetter: ");
    result.append(isSetter);
    result.append(", isGetter: ");
    result.append(isGetter);
    result.append(", functionName: ");
    result.append(functionName);
    result.append(", parameters: ");
    result.append(parameters);
    result.append(')');
    return result.toString();
  }

} //ActionImpl
