/**
 * generated by Xtext 2.21.0
 */
package xtext.robocode.generator.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.robocode.generator.AdvancedRobot;
import xtext.robocode.generator.GeneratorPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Advanced Robot</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AdvancedRobotImpl extends RobotImpl implements AdvancedRobot
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AdvancedRobotImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GeneratorPackage.Literals.ADVANCED_ROBOT;
  }

} //AdvancedRobotImpl
