/**
 * generated by Xtext 2.21.0
 */
package xtext.robocode.generator.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.robocode.generator.GeneratorPackage;
import xtext.robocode.generator.RangeControlRobot;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Range Control Robot</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RangeControlRobotImpl extends RobotImpl implements RangeControlRobot
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RangeControlRobotImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GeneratorPackage.Literals.RANGE_CONTROL_ROBOT;
  }

} //RangeControlRobotImpl
