/*
 * generated by Xtext 2.21.0
 */
package xtext.robocode.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GeneratorGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ArenaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.robocode.Generator.Arena");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cArenaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cRobotKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cRobotAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cRobotRobotParserRuleCall_2_2_0 = (RuleCall)cRobotAssignment_2_2.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cRobotAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cRobotRobotParserRuleCall_2_3_1_0 = (RuleCall)cRobotAssignment_2_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Arena:
		//	'Arena'
		//	'{' ('robot' '{' robot+=Robot ("," robot+=Robot)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Arena' '{' ('robot' '{' robot+=Robot ("," robot+=Robot)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'Arena'
		public Keyword getArenaKeyword_0() { return cArenaKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('robot' '{' robot+=Robot ("," robot+=Robot)* '}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'robot'
		public Keyword getRobotKeyword_2_0() { return cRobotKeyword_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_1() { return cLeftCurlyBracketKeyword_2_1; }
		
		//robot+=Robot
		public Assignment getRobotAssignment_2_2() { return cRobotAssignment_2_2; }
		
		//Robot
		public RuleCall getRobotRobotParserRuleCall_2_2_0() { return cRobotRobotParserRuleCall_2_2_0; }
		
		//("," robot+=Robot)*
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//","
		public Keyword getCommaKeyword_2_3_0() { return cCommaKeyword_2_3_0; }
		
		//robot+=Robot
		public Assignment getRobotAssignment_2_3_1() { return cRobotAssignment_2_3_1; }
		
		//Robot
		public RuleCall getRobotRobotParserRuleCall_2_3_1_0() { return cRobotRobotParserRuleCall_2_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_4() { return cRightCurlyBracketKeyword_2_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class RobotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.robocode.Generator.Robot");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRobot_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAdvancedRobot_ImplParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRangeControlRobotParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Robot:
		//	Robot_Impl | AdvancedRobot_Impl | RangeControlRobot;
		@Override public ParserRule getRule() { return rule; }
		
		//Robot_Impl | AdvancedRobot_Impl | RangeControlRobot
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Robot_Impl
		public RuleCall getRobot_ImplParserRuleCall_0() { return cRobot_ImplParserRuleCall_0; }
		
		//AdvancedRobot_Impl
		public RuleCall getAdvancedRobot_ImplParserRuleCall_1() { return cAdvancedRobot_ImplParserRuleCall_1; }
		
		//RangeControlRobot
		public RuleCall getRangeControlRobotParserRuleCall_2() { return cRangeControlRobotParserRuleCall_2; }
	}
	public class Robot_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.robocode.Generator.Robot_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRobotAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRobotKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEventsHandledKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cEventsHandledAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cEventsHandledEventParserRuleCall_4_2_0 = (RuleCall)cEventsHandledAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cEventsHandledAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cEventsHandledEventParserRuleCall_4_3_1_0 = (RuleCall)cEventsHandledAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRunActionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRunActionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cRunActionsActionParserRuleCall_5_2_0 = (RuleCall)cRunActionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cRunActionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cRunActionsActionParserRuleCall_5_3_1_0 = (RuleCall)cRunActionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cInfiniteLoopActionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cInfiniteLoopActionsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cInfiniteLoopActionsActionParserRuleCall_6_2_0 = (RuleCall)cInfiniteLoopActionsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cInfiniteLoopActionsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cInfiniteLoopActionsActionParserRuleCall_6_3_1_0 = (RuleCall)cInfiniteLoopActionsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Robot_Impl Robot:
		//	{Robot}
		//	'Robot'
		//	name=EString
		//	'{' ('eventsHandled' '(' eventsHandled+=Event ("," eventsHandled+=Event)* ')')? ('runActions' '{' runActions+=Action
		//	("," runActions+=Action)* '}')? ('infiniteLoopActions' '{' infiniteLoopActions+=Action (","
		//	infiniteLoopActions+=Action)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Robot} 'Robot' name=EString '{' ('eventsHandled' '(' eventsHandled+=Event ("," eventsHandled+=Event)* ')')?
		//('runActions' '{' runActions+=Action ("," runActions+=Action)* '}')? ('infiniteLoopActions' '{'
		//infiniteLoopActions+=Action ("," infiniteLoopActions+=Action)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Robot}
		public Action getRobotAction_0() { return cRobotAction_0; }
		
		//'Robot'
		public Keyword getRobotKeyword_1() { return cRobotKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('eventsHandled' '(' eventsHandled+=Event ("," eventsHandled+=Event)* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'eventsHandled'
		public Keyword getEventsHandledKeyword_4_0() { return cEventsHandledKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//eventsHandled+=Event
		public Assignment getEventsHandledAssignment_4_2() { return cEventsHandledAssignment_4_2; }
		
		//Event
		public RuleCall getEventsHandledEventParserRuleCall_4_2_0() { return cEventsHandledEventParserRuleCall_4_2_0; }
		
		//("," eventsHandled+=Event)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//eventsHandled+=Event
		public Assignment getEventsHandledAssignment_4_3_1() { return cEventsHandledAssignment_4_3_1; }
		
		//Event
		public RuleCall getEventsHandledEventParserRuleCall_4_3_1_0() { return cEventsHandledEventParserRuleCall_4_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('runActions' '{' runActions+=Action ("," runActions+=Action)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'runActions'
		public Keyword getRunActionsKeyword_5_0() { return cRunActionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//runActions+=Action
		public Assignment getRunActionsAssignment_5_2() { return cRunActionsAssignment_5_2; }
		
		//Action
		public RuleCall getRunActionsActionParserRuleCall_5_2_0() { return cRunActionsActionParserRuleCall_5_2_0; }
		
		//("," runActions+=Action)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//runActions+=Action
		public Assignment getRunActionsAssignment_5_3_1() { return cRunActionsAssignment_5_3_1; }
		
		//Action
		public RuleCall getRunActionsActionParserRuleCall_5_3_1_0() { return cRunActionsActionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('infiniteLoopActions' '{' infiniteLoopActions+=Action ("," infiniteLoopActions+=Action)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'infiniteLoopActions'
		public Keyword getInfiniteLoopActionsKeyword_6_0() { return cInfiniteLoopActionsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//infiniteLoopActions+=Action
		public Assignment getInfiniteLoopActionsAssignment_6_2() { return cInfiniteLoopActionsAssignment_6_2; }
		
		//Action
		public RuleCall getInfiniteLoopActionsActionParserRuleCall_6_2_0() { return cInfiniteLoopActionsActionParserRuleCall_6_2_0; }
		
		//("," infiniteLoopActions+=Action)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//infiniteLoopActions+=Action
		public Assignment getInfiniteLoopActionsAssignment_6_3_1() { return cInfiniteLoopActionsAssignment_6_3_1; }
		
		//Action
		public RuleCall getInfiniteLoopActionsActionParserRuleCall_6_3_1_0() { return cInfiniteLoopActionsActionParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.robocode.Generator.Event");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEventAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEventKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEventTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cEventTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cEventTypeEventTypeEnumRuleCall_3_1_0 = (RuleCall)cEventTypeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActionsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cActionsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cActionsActionParserRuleCall_4_2_0 = (RuleCall)cActionsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cActionsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cActionsActionParserRuleCall_4_3_1_0 = (RuleCall)cActionsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Event:
		//	{Event}
		//	'Event'
		//	'{' ('eventType' eventType=EventType)? ('actions' '{' actions+=Action ("," actions+=Action)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Event} 'Event' '{' ('eventType' eventType=EventType)? ('actions' '{' actions+=Action ("," actions+=Action)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Event}
		public Action getEventAction_0() { return cEventAction_0; }
		
		//'Event'
		public Keyword getEventKeyword_1() { return cEventKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('eventType' eventType=EventType)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'eventType'
		public Keyword getEventTypeKeyword_3_0() { return cEventTypeKeyword_3_0; }
		
		//eventType=EventType
		public Assignment getEventTypeAssignment_3_1() { return cEventTypeAssignment_3_1; }
		
		//EventType
		public RuleCall getEventTypeEventTypeEnumRuleCall_3_1_0() { return cEventTypeEventTypeEnumRuleCall_3_1_0; }
		
		//('actions' '{' actions+=Action ("," actions+=Action)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'actions'
		public Keyword getActionsKeyword_4_0() { return cActionsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//actions+=Action
		public Assignment getActionsAssignment_4_2() { return cActionsAssignment_4_2; }
		
		//Action
		public RuleCall getActionsActionParserRuleCall_4_2_0() { return cActionsActionParserRuleCall_4_2_0; }
		
		//("," actions+=Action)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//actions+=Action
		public Assignment getActionsAssignment_4_3_1() { return cActionsAssignment_4_3_1; }
		
		//Action
		public RuleCall getActionsActionParserRuleCall_4_3_1_0() { return cActionsActionParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.robocode.Generator.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.robocode.Generator.Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommentKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cCommentAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cCommentEStringParserRuleCall_2_1_0 = (RuleCall)cCommentAssignment_2_1.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cIsSetterAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final Keyword cIsSetterSetterKeyword_3_0_0 = (Keyword)cIsSetterAssignment_3_0.eContents().get(0);
		private final Assignment cIsGetterAssignment_3_1 = (Assignment)cAlternatives_3.eContents().get(1);
		private final Keyword cIsGetterGetterKeyword_3_1_0 = (Keyword)cIsGetterAssignment_3_1.eContents().get(0);
		private final Keyword cFunctionNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFunctionNameAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFunctionNameEStringParserRuleCall_5_0 = (RuleCall)cFunctionNameAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cParametersKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cParametersAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cParametersEStringParserRuleCall_6_1_0 = (RuleCall)cParametersAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Action:
		//	'Action'
		//	'{' ('comment' comment=EString)? (isSetter?="setter" | isGetter?="getter")?
		//	'functionName' functionName=EString ('parameters' parameters=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Action' '{' ('comment' comment=EString)? (isSetter?="setter" | isGetter?="getter")? 'functionName' functionName=EString
		//('parameters' parameters=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Action'
		public Keyword getActionKeyword_0() { return cActionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('comment' comment=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'comment'
		public Keyword getCommentKeyword_2_0() { return cCommentKeyword_2_0; }
		
		//comment=EString
		public Assignment getCommentAssignment_2_1() { return cCommentAssignment_2_1; }
		
		//EString
		public RuleCall getCommentEStringParserRuleCall_2_1_0() { return cCommentEStringParserRuleCall_2_1_0; }
		
		//(isSetter?="setter" | isGetter?="getter")?
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//isSetter?="setter"
		public Assignment getIsSetterAssignment_3_0() { return cIsSetterAssignment_3_0; }
		
		//"setter"
		public Keyword getIsSetterSetterKeyword_3_0_0() { return cIsSetterSetterKeyword_3_0_0; }
		
		//isGetter?="getter"
		public Assignment getIsGetterAssignment_3_1() { return cIsGetterAssignment_3_1; }
		
		//"getter"
		public Keyword getIsGetterGetterKeyword_3_1_0() { return cIsGetterGetterKeyword_3_1_0; }
		
		//'functionName'
		public Keyword getFunctionNameKeyword_4() { return cFunctionNameKeyword_4; }
		
		//functionName=EString
		public Assignment getFunctionNameAssignment_5() { return cFunctionNameAssignment_5; }
		
		//EString
		public RuleCall getFunctionNameEStringParserRuleCall_5_0() { return cFunctionNameEStringParserRuleCall_5_0; }
		
		//('parameters' parameters=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'parameters'
		public Keyword getParametersKeyword_6_0() { return cParametersKeyword_6_0; }
		
		//parameters=EString
		public Assignment getParametersAssignment_6_1() { return cParametersAssignment_6_1; }
		
		//EString
		public RuleCall getParametersEStringParserRuleCall_6_1_0() { return cParametersEStringParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class AdvancedRobot_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.robocode.Generator.AdvancedRobot_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAdvancedRobotAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAdvancedRobotKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEventsHandledKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cEventsHandledAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cEventsHandledEventParserRuleCall_4_2_0 = (RuleCall)cEventsHandledAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cEventsHandledAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cEventsHandledEventParserRuleCall_4_3_1_0 = (RuleCall)cEventsHandledAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRunActionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRunActionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cRunActionsActionParserRuleCall_5_2_0 = (RuleCall)cRunActionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cRunActionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cRunActionsActionParserRuleCall_5_3_1_0 = (RuleCall)cRunActionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cInfiniteLoopActionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cInfiniteLoopActionsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cInfiniteLoopActionsActionParserRuleCall_6_2_0 = (RuleCall)cInfiniteLoopActionsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cInfiniteLoopActionsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cInfiniteLoopActionsActionParserRuleCall_6_3_1_0 = (RuleCall)cInfiniteLoopActionsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//AdvancedRobot_Impl AdvancedRobot:
		//	{AdvancedRobot}
		//	'AdvancedRobot'
		//	name=EString
		//	'{' ('eventsHandled' '(' eventsHandled+=Event ("," eventsHandled+=Event)* ')')? ('runActions' '{' runActions+=Action
		//	("," runActions+=Action)* '}')? ('infiniteLoopActions' '{' infiniteLoopActions+=Action (","
		//	infiniteLoopActions+=Action)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{AdvancedRobot} 'AdvancedRobot' name=EString '{' ('eventsHandled' '(' eventsHandled+=Event ("," eventsHandled+=Event)*
		//')')? ('runActions' '{' runActions+=Action ("," runActions+=Action)* '}')? ('infiniteLoopActions' '{'
		//infiniteLoopActions+=Action ("," infiniteLoopActions+=Action)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{AdvancedRobot}
		public Action getAdvancedRobotAction_0() { return cAdvancedRobotAction_0; }
		
		//'AdvancedRobot'
		public Keyword getAdvancedRobotKeyword_1() { return cAdvancedRobotKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('eventsHandled' '(' eventsHandled+=Event ("," eventsHandled+=Event)* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'eventsHandled'
		public Keyword getEventsHandledKeyword_4_0() { return cEventsHandledKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//eventsHandled+=Event
		public Assignment getEventsHandledAssignment_4_2() { return cEventsHandledAssignment_4_2; }
		
		//Event
		public RuleCall getEventsHandledEventParserRuleCall_4_2_0() { return cEventsHandledEventParserRuleCall_4_2_0; }
		
		//("," eventsHandled+=Event)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//eventsHandled+=Event
		public Assignment getEventsHandledAssignment_4_3_1() { return cEventsHandledAssignment_4_3_1; }
		
		//Event
		public RuleCall getEventsHandledEventParserRuleCall_4_3_1_0() { return cEventsHandledEventParserRuleCall_4_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('runActions' '{' runActions+=Action ("," runActions+=Action)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'runActions'
		public Keyword getRunActionsKeyword_5_0() { return cRunActionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//runActions+=Action
		public Assignment getRunActionsAssignment_5_2() { return cRunActionsAssignment_5_2; }
		
		//Action
		public RuleCall getRunActionsActionParserRuleCall_5_2_0() { return cRunActionsActionParserRuleCall_5_2_0; }
		
		//("," runActions+=Action)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//runActions+=Action
		public Assignment getRunActionsAssignment_5_3_1() { return cRunActionsAssignment_5_3_1; }
		
		//Action
		public RuleCall getRunActionsActionParserRuleCall_5_3_1_0() { return cRunActionsActionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('infiniteLoopActions' '{' infiniteLoopActions+=Action ("," infiniteLoopActions+=Action)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'infiniteLoopActions'
		public Keyword getInfiniteLoopActionsKeyword_6_0() { return cInfiniteLoopActionsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//infiniteLoopActions+=Action
		public Assignment getInfiniteLoopActionsAssignment_6_2() { return cInfiniteLoopActionsAssignment_6_2; }
		
		//Action
		public RuleCall getInfiniteLoopActionsActionParserRuleCall_6_2_0() { return cInfiniteLoopActionsActionParserRuleCall_6_2_0; }
		
		//("," infiniteLoopActions+=Action)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//infiniteLoopActions+=Action
		public Assignment getInfiniteLoopActionsAssignment_6_3_1() { return cInfiniteLoopActionsAssignment_6_3_1; }
		
		//Action
		public RuleCall getInfiniteLoopActionsActionParserRuleCall_6_3_1_0() { return cInfiniteLoopActionsActionParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class RangeControlRobotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.robocode.Generator.RangeControlRobot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRangeControlRobotAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRangeControlRobotKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEventsHandledKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cEventsHandledAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cEventsHandledEventParserRuleCall_4_2_0 = (RuleCall)cEventsHandledAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cEventsHandledAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cEventsHandledEventParserRuleCall_4_3_1_0 = (RuleCall)cEventsHandledAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRunActionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRunActionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cRunActionsActionParserRuleCall_5_2_0 = (RuleCall)cRunActionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cRunActionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cRunActionsActionParserRuleCall_5_3_1_0 = (RuleCall)cRunActionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cInfiniteLoopActionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cInfiniteLoopActionsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cInfiniteLoopActionsActionParserRuleCall_6_2_0 = (RuleCall)cInfiniteLoopActionsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cInfiniteLoopActionsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cInfiniteLoopActionsActionParserRuleCall_6_3_1_0 = (RuleCall)cInfiniteLoopActionsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RangeControlRobot:
		//	{RangeControlRobot}
		//	'RangeControlRobot'
		//	name=EString
		//	'{' ('eventsHandled' '(' eventsHandled+=Event ("," eventsHandled+=Event)* ')')? ('runActions' '{' runActions+=Action
		//	("," runActions+=Action)* '}')? ('infiniteLoopActions' '{' infiniteLoopActions+=Action (","
		//	infiniteLoopActions+=Action)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RangeControlRobot} 'RangeControlRobot' name=EString '{' ('eventsHandled' '(' eventsHandled+=Event (","
		//eventsHandled+=Event)* ')')? ('runActions' '{' runActions+=Action ("," runActions+=Action)* '}')?
		//('infiniteLoopActions' '{' infiniteLoopActions+=Action ("," infiniteLoopActions+=Action)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{RangeControlRobot}
		public Action getRangeControlRobotAction_0() { return cRangeControlRobotAction_0; }
		
		//'RangeControlRobot'
		public Keyword getRangeControlRobotKeyword_1() { return cRangeControlRobotKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('eventsHandled' '(' eventsHandled+=Event ("," eventsHandled+=Event)* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'eventsHandled'
		public Keyword getEventsHandledKeyword_4_0() { return cEventsHandledKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//eventsHandled+=Event
		public Assignment getEventsHandledAssignment_4_2() { return cEventsHandledAssignment_4_2; }
		
		//Event
		public RuleCall getEventsHandledEventParserRuleCall_4_2_0() { return cEventsHandledEventParserRuleCall_4_2_0; }
		
		//("," eventsHandled+=Event)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//eventsHandled+=Event
		public Assignment getEventsHandledAssignment_4_3_1() { return cEventsHandledAssignment_4_3_1; }
		
		//Event
		public RuleCall getEventsHandledEventParserRuleCall_4_3_1_0() { return cEventsHandledEventParserRuleCall_4_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('runActions' '{' runActions+=Action ("," runActions+=Action)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'runActions'
		public Keyword getRunActionsKeyword_5_0() { return cRunActionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//runActions+=Action
		public Assignment getRunActionsAssignment_5_2() { return cRunActionsAssignment_5_2; }
		
		//Action
		public RuleCall getRunActionsActionParserRuleCall_5_2_0() { return cRunActionsActionParserRuleCall_5_2_0; }
		
		//("," runActions+=Action)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//runActions+=Action
		public Assignment getRunActionsAssignment_5_3_1() { return cRunActionsAssignment_5_3_1; }
		
		//Action
		public RuleCall getRunActionsActionParserRuleCall_5_3_1_0() { return cRunActionsActionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('infiniteLoopActions' '{' infiniteLoopActions+=Action ("," infiniteLoopActions+=Action)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'infiniteLoopActions'
		public Keyword getInfiniteLoopActionsKeyword_6_0() { return cInfiniteLoopActionsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//infiniteLoopActions+=Action
		public Assignment getInfiniteLoopActionsAssignment_6_2() { return cInfiniteLoopActionsAssignment_6_2; }
		
		//Action
		public RuleCall getInfiniteLoopActionsActionParserRuleCall_6_2_0() { return cInfiniteLoopActionsActionParserRuleCall_6_2_0; }
		
		//("," infiniteLoopActions+=Action)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//infiniteLoopActions+=Action
		public Assignment getInfiniteLoopActionsAssignment_6_3_1() { return cInfiniteLoopActionsAssignment_6_3_1; }
		
		//Action
		public RuleCall getInfiniteLoopActionsActionParserRuleCall_6_3_1_0() { return cInfiniteLoopActionsActionParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	public class EventTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.robocode.Generator.EventType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBulletHitEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBulletHitBulletHitKeyword_0_0 = (Keyword)cBulletHitEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBulletMissedEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBulletMissedBulletMissedKeyword_1_0 = (Keyword)cBulletMissedEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDeathEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDeathDeathKeyword_2_0 = (Keyword)cDeathEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cHitByBulletEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cHitByBulletHitByBulletKeyword_3_0 = (Keyword)cHitByBulletEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cHitRobotEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cHitRobotHitRobotKeyword_4_0 = (Keyword)cHitRobotEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cHitWallEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cHitWallHitWallKeyword_5_0 = (Keyword)cHitWallEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cScannedRobotEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cScannedRobotScannedRobotKeyword_6_0 = (Keyword)cScannedRobotEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cWinEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cWinWinKeyword_7_0 = (Keyword)cWinEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cCustomEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cCustomCustomKeyword_8_0 = (Keyword)cCustomEnumLiteralDeclaration_8.eContents().get(0);
		
		//enum EventType:
		//	BulletHit | BulletMissed | Death | HitByBullet | HitRobot | HitWall | ScannedRobot | Win | Custom;
		public EnumRule getRule() { return rule; }
		
		//BulletHit | BulletMissed | Death | HitByBullet | HitRobot | HitWall | ScannedRobot | Win | Custom
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BulletHit
		public EnumLiteralDeclaration getBulletHitEnumLiteralDeclaration_0() { return cBulletHitEnumLiteralDeclaration_0; }
		
		//'BulletHit'
		public Keyword getBulletHitBulletHitKeyword_0_0() { return cBulletHitBulletHitKeyword_0_0; }
		
		//BulletMissed
		public EnumLiteralDeclaration getBulletMissedEnumLiteralDeclaration_1() { return cBulletMissedEnumLiteralDeclaration_1; }
		
		//'BulletMissed'
		public Keyword getBulletMissedBulletMissedKeyword_1_0() { return cBulletMissedBulletMissedKeyword_1_0; }
		
		//Death
		public EnumLiteralDeclaration getDeathEnumLiteralDeclaration_2() { return cDeathEnumLiteralDeclaration_2; }
		
		//'Death'
		public Keyword getDeathDeathKeyword_2_0() { return cDeathDeathKeyword_2_0; }
		
		//HitByBullet
		public EnumLiteralDeclaration getHitByBulletEnumLiteralDeclaration_3() { return cHitByBulletEnumLiteralDeclaration_3; }
		
		//'HitByBullet'
		public Keyword getHitByBulletHitByBulletKeyword_3_0() { return cHitByBulletHitByBulletKeyword_3_0; }
		
		//HitRobot
		public EnumLiteralDeclaration getHitRobotEnumLiteralDeclaration_4() { return cHitRobotEnumLiteralDeclaration_4; }
		
		//'HitRobot'
		public Keyword getHitRobotHitRobotKeyword_4_0() { return cHitRobotHitRobotKeyword_4_0; }
		
		//HitWall
		public EnumLiteralDeclaration getHitWallEnumLiteralDeclaration_5() { return cHitWallEnumLiteralDeclaration_5; }
		
		//'HitWall'
		public Keyword getHitWallHitWallKeyword_5_0() { return cHitWallHitWallKeyword_5_0; }
		
		//ScannedRobot
		public EnumLiteralDeclaration getScannedRobotEnumLiteralDeclaration_6() { return cScannedRobotEnumLiteralDeclaration_6; }
		
		//'ScannedRobot'
		public Keyword getScannedRobotScannedRobotKeyword_6_0() { return cScannedRobotScannedRobotKeyword_6_0; }
		
		//Win
		public EnumLiteralDeclaration getWinEnumLiteralDeclaration_7() { return cWinEnumLiteralDeclaration_7; }
		
		//'Win'
		public Keyword getWinWinKeyword_7_0() { return cWinWinKeyword_7_0; }
		
		//Custom
		public EnumLiteralDeclaration getCustomEnumLiteralDeclaration_8() { return cCustomEnumLiteralDeclaration_8; }
		
		//'Custom'
		public Keyword getCustomCustomKeyword_8_0() { return cCustomCustomKeyword_8_0; }
	}
	
	private final ArenaElements pArena;
	private final RobotElements pRobot;
	private final Robot_ImplElements pRobot_Impl;
	private final EventElements pEvent;
	private final EStringElements pEString;
	private final ActionElements pAction;
	private final AdvancedRobot_ImplElements pAdvancedRobot_Impl;
	private final RangeControlRobotElements pRangeControlRobot;
	private final EventTypeElements eEventType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GeneratorGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pArena = new ArenaElements();
		this.pRobot = new RobotElements();
		this.pRobot_Impl = new Robot_ImplElements();
		this.pEvent = new EventElements();
		this.pEString = new EStringElements();
		this.pAction = new ActionElements();
		this.pAdvancedRobot_Impl = new AdvancedRobot_ImplElements();
		this.pRangeControlRobot = new RangeControlRobotElements();
		this.eEventType = new EventTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("xtext.robocode.Generator".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Arena:
	//	'Arena'
	//	'{' ('robot' '{' robot+=Robot ("," robot+=Robot)* '}')?
	//	'}';
	public ArenaElements getArenaAccess() {
		return pArena;
	}
	
	public ParserRule getArenaRule() {
		return getArenaAccess().getRule();
	}
	
	//Robot:
	//	Robot_Impl | AdvancedRobot_Impl | RangeControlRobot;
	public RobotElements getRobotAccess() {
		return pRobot;
	}
	
	public ParserRule getRobotRule() {
		return getRobotAccess().getRule();
	}
	
	//Robot_Impl Robot:
	//	{Robot}
	//	'Robot'
	//	name=EString
	//	'{' ('eventsHandled' '(' eventsHandled+=Event ("," eventsHandled+=Event)* ')')? ('runActions' '{' runActions+=Action
	//	("," runActions+=Action)* '}')? ('infiniteLoopActions' '{' infiniteLoopActions+=Action (","
	//	infiniteLoopActions+=Action)* '}')?
	//	'}';
	public Robot_ImplElements getRobot_ImplAccess() {
		return pRobot_Impl;
	}
	
	public ParserRule getRobot_ImplRule() {
		return getRobot_ImplAccess().getRule();
	}
	
	//Event:
	//	{Event}
	//	'Event'
	//	'{' ('eventType' eventType=EventType)? ('actions' '{' actions+=Action ("," actions+=Action)* '}')?
	//	'}';
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Action:
	//	'Action'
	//	'{' ('comment' comment=EString)? (isSetter?="setter" | isGetter?="getter")?
	//	'functionName' functionName=EString ('parameters' parameters=EString)?
	//	'}';
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//AdvancedRobot_Impl AdvancedRobot:
	//	{AdvancedRobot}
	//	'AdvancedRobot'
	//	name=EString
	//	'{' ('eventsHandled' '(' eventsHandled+=Event ("," eventsHandled+=Event)* ')')? ('runActions' '{' runActions+=Action
	//	("," runActions+=Action)* '}')? ('infiniteLoopActions' '{' infiniteLoopActions+=Action (","
	//	infiniteLoopActions+=Action)* '}')?
	//	'}';
	public AdvancedRobot_ImplElements getAdvancedRobot_ImplAccess() {
		return pAdvancedRobot_Impl;
	}
	
	public ParserRule getAdvancedRobot_ImplRule() {
		return getAdvancedRobot_ImplAccess().getRule();
	}
	
	//RangeControlRobot:
	//	{RangeControlRobot}
	//	'RangeControlRobot'
	//	name=EString
	//	'{' ('eventsHandled' '(' eventsHandled+=Event ("," eventsHandled+=Event)* ')')? ('runActions' '{' runActions+=Action
	//	("," runActions+=Action)* '}')? ('infiniteLoopActions' '{' infiniteLoopActions+=Action (","
	//	infiniteLoopActions+=Action)* '}')?
	//	'}';
	public RangeControlRobotElements getRangeControlRobotAccess() {
		return pRangeControlRobot;
	}
	
	public ParserRule getRangeControlRobotRule() {
		return getRangeControlRobotAccess().getRule();
	}
	
	//enum EventType:
	//	BulletHit | BulletMissed | Death | HitByBullet | HitRobot | HitWall | ScannedRobot | Win | Custom;
	public EventTypeElements getEventTypeAccess() {
		return eEventType;
	}
	
	public EnumRule getEventTypeRule() {
		return getEventTypeAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
