/*
 * generated by Xtext 2.21.0
 */
package xtext.robocode.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.robocode.parser.antlr.internal.InternalGeneratorParser;
import xtext.robocode.services.GeneratorGrammarAccess;

public class GeneratorParser extends AbstractAntlrParser {

	@Inject
	private GeneratorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGeneratorParser createParser(XtextTokenStream stream) {
		return new InternalGeneratorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Arena";
	}

	public GeneratorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GeneratorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
