/*
 * generated by Xtext 2.21.0
 */
package xtext.robocode.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GeneratorUiModule extends AbstractGeneratorUiModule {

	public GeneratorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
