/*
 * generated by Xtext 2.21.0
 */
package xtext.robocode.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.robocode.GeneratorRuntimeModule;
import xtext.robocode.GeneratorStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GeneratorIdeSetup extends GeneratorStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GeneratorRuntimeModule(), new GeneratorIdeModule()));
	}
	
}
