/*
 * generated by Xtext 2.21.0
 */
package xtext.robocode.ide;


/**
 * Use this class to register ide components.
 */
public class GeneratorIdeModule extends AbstractGeneratorIdeModule {
}
