/*
 * generated by Xtext 2.21.0
 */
package xtext.robocode.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.robocode.generator.ui.internal.GeneratorActivator;

public class GeneratorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GeneratorActivator.getInstance().getInjector("xtext.robocode.Generator");
	}

}
